# Generated by Django 4.2.11 on 2025-11-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('iframe', models.TextField(blank=True, max_length=5000, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
