# Generated by Django 4.2.11 on 2025-11-07 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='business_document',
            field=models.FileField(blank=True, null=True, upload_to='shops/documents/'),
        ),
        migrations.CreateModel(
            name='DispatcherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('plate_number', models.CharField(blank=True, max_length=50)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='dispatchers/documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
