# Generated by Django 4.2.11 on 2026-01-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_remove_profile_email_confirmed_profile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
