# Generated by Codex on 2026-01-31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_shop_followers_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="currency",
            field=models.CharField(default="NGN", max_length=8),
        ),
        migrations.AddField(
            model_name="shop",
            name="weight_unit",
            field=models.CharField(choices=[("kg", "Kilogram (kg)"), ("g", "Gram (g)"), ("lb", "Pound (lb)"), ("oz", "Ounce (oz)"), ("unit", "Unit")], default="kg", max_length=10),
        ),
        migrations.CreateModel(
            name="ShopIntegration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("shopify", "Shopify"), ("square", "Square"), ("quickbooks", "QuickBooks")], max_length=50)),
                ("access_token", models.CharField(blank=True, max_length=255)),
                ("refresh_token", models.CharField(blank=True, max_length=255)),
                ("external_store_id", models.CharField(blank=True, max_length=255)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_status", models.CharField(default="pending", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="integrations", to="account.shop")),
            ],
        ),
        migrations.AddConstraint(
            model_name="shopintegration",
            constraint=models.UniqueConstraint(fields=("shop", "provider"), name="unique_shop_provider"),
        ),
    ]
