# Generated by Django 4.2.11 on 2026-01-29 12:00

from django.db import migrations, models


def populate_signup_emails(apps, schema_editor):
    Signup = apps.get_model("marketing", "Signup")
    for signup in Signup.objects.filter(email__isnull=True):
        signup.email = f"unknown+{signup.id}@example.com"
        signup.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_signup_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
