# Generated by Django 4.2.11 on 2026-01-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodCreate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name="products",
            index_together={("id", "slug")},
        ),
    ]
