# Generated by Django 4.2.11 on 2026-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodCreate", "0002_products_expires_on_alter_products_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="expires_on",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="products",
            constraint=models.UniqueConstraint(
                fields=("shop", "slug"), name="unique_shop_slug"
            ),
        ),
    ]
