# Generated by Codex on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodCreate", "0004_alter_products_discount_price_alter_products_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="barcode",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
